# This is a basic workflow to help you get started with Actions
name: Terraform deployment

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master
  workflow_dispatch:
    # inputs:
    #   name:
    #     description: "Who to greet"
    #     default: "World" # Ref :${{ github.event.inputs.name }}"

env:
  AWS_REGION: ap-south-1 #Change to reflect your Region
  WORKING_DIRECTORY: environments/dev

# Permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  pull-requests: write

jobs:
  TerraformPlan:
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    outputs:
      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Print directory and List files
        run: |
          pwd
          ls -lhrta

      - name: Setup JQ
        uses: dcarbone/install-jq-action@v2.1.0

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE }} #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.5"

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: false

      - name: Terraform Init
        run: terraform init -backend-config=backend.conf

      - name: Load tfvars
        run: |
          aws ssm get-parameter --name '${{ vars.SSM_PATH }}' | jq -r '.Parameter.Value' > terraform.tfvars

      - name: Terraform Plan
        id: tf-plan
        run: |
          export exitcode=0
          terraform plan -detailed-exitcode -no-color -out tfplan 
          terraform show --json tfplan > tfplan.json

          export exitcode=$?

          printf '%s\n' "$exitcode" # This will output 'exitcode'

          echo "exitcode=$exitcode" >> $GITHUB_ENV

          if [ $exitcode -eq 1 ]; then
            echo Terraform Plan Failed!
            exit 1
          else 
            exit 0
          fi

      - name: Print ExitCode
        run: |
          echo "Output from job1: ${{ steps.tf-plan.outputs.exitcode }}"
          printf '%s\n' "$exitcode" # This will output 'exitcode'

      # - name: Publish Terraform Plan
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: tfplan
      #     path: ${{ env.WORKING_DIRECTORY }}/tfplan

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      - name: Run OPA Tests
        id: opa-tests
        run: |
          output=$(opa eval --data ../../tests/check-tags.rego --input tfplan.json "data.terraform.aws.common.deny" | jq '{deny: .result[0].expressions[0].value}')
          echo "opa_output=$output" >> $GITHUB_ENV
          if [ $output| jq '.deny' | jq length ]; then
            echo "OPA policy violations found"
            cat $output
            exit 1
          else
            echo "No OPA policy violations found."
          fi

      # Create string output of Terraform Plan
      - name: Create String Output
        id: tf-plan-string
        run: |
          TERRAFORM_PLAN=$(terraform show -no-color tfplan)

          delimiter="$(openssl rand -hex 8)"
          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
          echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo '```terraform' >> $GITHUB_OUTPUT
          echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "</details>" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT

      - name: Publish Terraform Plan to Task Summary
        env:
          SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
        run: |
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

  TerraformApply:
    runs-on: ubuntu-latest
    environment: development
    needs: [TerraformPlan]
    if: github.ref == 'refs/heads/dev' && needs.TerraformPlan.outputs.tfplanExitCode == 2
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE }} #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.5"

      - name: Terraform Init
        run: terraform init -backend-config=backend.conf

      - name: Load tfvars
        run: |
          aws ssm get-parameter --name '${{ vars.SSM_PATH }}' | jq -r '.Parameter.Value' > terraform.tfvars

      - name: Terraform Apply
        run: terraform apply -auto-approve
