# This is a basic workflow to help you get started with Actions
name: Terraform deployment   

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master
  workflow_dispatch:
    # inputs:
    #   name:
    #     description: "Who to greet"
    #     default: "World" # Ref :${{ github.event.inputs.name }}"

env:
  AWS_REGION : ap-south-1 #Change to reflect your Region
  WORKING_DIRECTORY: environments/dev

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  TerraformPlan:
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE }} #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: List files
        run: |
          ls -lhrta

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.5"
      
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: false

      - name: Terraform Init
        run: terraform init -backend-config=backend.conf

      - name: Terraform Plan
        run: terraform plan -no-color
        continue-on-error: true